### ISSUE TITLE
Can not re-connect to audible account

### ISSUE THREAD

**Issue by guenth** [openaudible/openaudible#1169]
**Summary:**
I am a previous user who can not seem to re-connect to their audible account using on a system that was previously working with Openaudible.  

So far the problem seems to exist in Linux (Manjaro) re-installed (over an older version) with the install shell script - and on an M1 mac (fresh install via homebrew).

I logged out of the account in openaudible, but cannot reconnect/register it.  
The login process (including MFA/CAPTCHA) seems to be ok.
The error message in the pop-up suggests deactivating devices registered to the account - but I have deregistered them all and it did not solve the issue.

**Details:**
I renewed my license after not using it for a little over a year (not due to problems, just wasn't using audible much).
I upgraded to the latest version on my main desktop (Manjaro linux) via the shell script method, but I was having problems reconnecting to the account.  

Most of my testing has been on Manjaro Linux, but I did try from an M1 Mac (using the latest version - not the beta).

What I've tried:
- logging out and reconnecting (fails)
- running from an appimage (same issues as shell install)
- upgrading to the beta - OpenAudible_3.7.0.1_beta_x86_64.sh
- deregistering all audible devices from my account
- I tried installing the latest version on the mac - via homebrew. 
    - it seemed to have the same behavior, but I can not confirm the console output was the same.  Just that it suggests deregistering devices from my audible account.

I do have MFA on the account - but all that seems to be working properly.  (I have been setting the check boxes during the process to not require mfa for this browser).

So I am not sort of out of ideas - aside from finding a Windows box to try this one... 

Without going too crazy initially with console output - here is the stack trace and resulting error messages:

```
 "uri": "https://api.amazon.com/auth/register"
}
	at org.openaudible.util.HTTPUtil.postJSON(HTTPUtil.java:193)
	at org.openaudible.audible.api.Register.register(Register.java:278)
	at org.openaudible.audible.APIManager.registerDevice(APIManager.java:226)
	at org.openaudible.audible.APIManager.takeLogin(APIManager.java:150)
	at org.openaudible.desktop.swt.manager.login.LoginInternal.handleMapLanding(LoginInternal.java:125)
	at org.openaudible.desktop.swt.manager.login.LoginInternal.takeURL(LoginInternal.java:163)
	at org.openaudible.desktop.swt.manager.login.LoginInternal.browserEvent(LoginInternal.java:190)
	at org.openaudible.desktop.swt.manager.browser.BrowserManager.browserEvent(BrowserManager.java:170)
	at org.openaudible.desktop.swt.manager.browser.swt.AudibleBrowser$1OurLocationListener.changed(AudibleBrowser.java:102)
	at org.eclipse.swt.browser.WebKit.lambda$6(WebKit.java:1746)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5040)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4520)
	at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:291)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:391)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:133)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:146)
	at org.openaudible.desktop.Application.main(Application.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:71)
	at install4j.org.openaudible.desktop.Application.main(Unknown Source)

Mar 20, 2023 5:31:16 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: Error registering virtual device
Error creating a virtual device to communicate with Audible. You may need to delete some of your registered audible devices. Visit https://help.audible.com/s/article/how-can-i-deactivate-devices-that-are-using-the-audible-app
Check the Console for more details.
Mar 20, 2023 5:32:02 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:Error registering virtual device body:Error creating a virtual device to communicate with Audible. You may need to delete some of your registered audible devices. Visit https://help.audible.com/s/article/how-can-i-deactivate-devices-that-are-using-the-audible-app
Check the Console for more details. response:BUTTON_OK
```

**Comment by openaudible** [comment]
Can you send a bug report from the help menu, please?

**Comment by openaudible** [comment]
Hey, I was able to turn on voice over for OpenAudible and yes, it appears to work.
Click on the Library Status: Converting/Downloading number. That will select the books currently downloading or converting.
Then select one item from the table. Then hover over the State: in Audiobook Info panel. 
Good luck and feel free to reopen this or comment if you have any questions or suggestions.

**Comment by jessearmstrong** [comment]
I am having the same issue Just tried with 3.7.1 with no change

**Comment by guenth** [comment]
No luck with the web based one after upgrading to 3.7.1.  I will try the dialog based one - I didn't realize it would work w/ mfa.

**Comment by guenth** [comment]
The dialog based one also failed.  Bug report sent from the app.

**Comment by hjbarraza** [comment]
> The dialog based one also failed. Bug report sent from the app.

Version 3.6.1 worked for me

**Comment by openaudible** [comment]
Ok. Reproduced. Seems like a Mac problem. Working on a solution.

**Comment by openaudible** [comment]
Fixed the web browser login for Mac:
https://openaudible.org/beta

**Comment by MelB2702** [comment]
There is no download for 3.7.2 (it is still 3.7.1).

**Comment by openaudible** [comment]
Sorry. Fixed.

**Comment by MelB2702** [comment]
Wow, that was fast. Thank you. 

I still have login problems. Not fixed for me :( . (to many devices)

**Comment by blurfl** [comment]
I'm receiving the 'too many devices' error from this too. I have only one device registered, so the number of devices can't be the issue.

**Comment by guenth** [comment]
This still does not work for me.  I will send in a new bug report from the app (using this issue number)
