### ISSUE TITLE
Split Function is Not Working - Truncating The Audiobooks

### ISSUE THREAD

**Issue by TheDudeofDudeom** [openaudible/openaudible#1177]
I've tested two separate audiobooks and the split function is truncating the audiobooks by a great deal.  One audiobook  was 14 hours in length and truncated down to 1.5 hours.  A second over 23 hours and truncated down to 1 hour.

The individual MP3 file is the full length book so it is a split function issue.

**Comment by openaudible** [comment]
Sometimes the chapter data can be wrong from Audible. Or there could be a bug. 

Make sure you've deleted the destination directory for the split book and it does a new split process. (Some old versions did have some nasty truncation bugs that were fixed, but we think the split code hasn't changed in a while, but anything is possible.)

Can you select the book and do a "Get Info" and look at the Chapters tab?
It should show what the split will do -- create one file per chapter of the Chapter Length.

I did see a bug report and will take a look to see if I notice anything. 

Duplicate of #1778. Investigating that one too.

**Comment by openaudible** [comment]
I got your bug reports. It looks like the chapter data is invalid.
That said, we may be able to repair it.. since it seems like just some chapters are missing.
Reviewing. Will try to make a fix and post a beta.. the number of chapters may still be wrong, but hopefully whatever chapters are there can be expanded so missing audio data isn't lost.

**Comment by openaudible** [comment]
We looked at all the books in our library and found the chapter data can be wrong.. but it can be corrected (with a little guesswork.) 
Give the beta a try: 
https://openaudible.org/beta

**Comment by TheDudeofDudeom** [comment]
Thank you.  I installed the beta and cleared out all my books from OpenAudible, restarted, and still see some chapter data is incorrect.  But yes, with some guesswork it can be corrected.

I didn't have any issues with the previous OpenAudible version.  Unsure what has changed with the previous version to current.

**Comment by openaudible** [comment]
OK. We get the chapter data from the API and from the book itself. Sometimes they don't match up.. and sometimes there are gaps in the chapters. We can either add a chapter to fill in the gap, or extend the previous one to match the next chapter. We have to make a guess as to which chapter data is "more correct".. and we log a bunch of data to go along with it in case the chapters don't turn out right-- at least you can follow along with our guesses.  Added to 3.7.4.
