### ISSUE TITLE
test all now makes the text inside the frame vanish completly

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#1359]
before
![image](https://github.com/openaudible/openaudible/assets/1029921/35f7fd1f-c701-49f2-89d5-7dfca276bba7)

after pressing test all the text inside the frame vanishes before it was just hard to read.....

![image](https://github.com/openaudible/openaudible/assets/1029921/20b13d5a-7b60-4df4-90a8-bb73567f7abf)

Feb 29, 2024 5:08:30 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 4.1 for win32 swt 4963 jvm 18.0.1
Feb 29, 2024 5:08:30 PM org.openaudible.Directories load
INFO: Loading directories. These must be online and read/writable:
->{
 "ZIP": "",
 "META": "C:\\Users\\Lee Mackinnell\\OpenAudible",
 "APP": "C:\\Program Files\\OpenAudible",
 "ART": "",
 "BOOKS": "",
 "BASE": "P:\\Plex Extra\\OpenAudibleFiles",
 "MP3": "",
 "PDF": "",
 "WEB": "P:\\Plex Extra\\OpenAudibleFiles",
 "TMP": "C:\\Users\\Lee Mackinnell\\OpenAudible\\tmp",
 "AAX": "",
 "M4B": "",
 "M4A": ""
}
Feb 29, 2024 5:08:30 PM org.openaudible.Directories getPrefs
INFO: Loading C:\Users\Lee Mackinnell\OpenAudible\settings.json exists=true size=623
Feb 29, 2024 5:08:30 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1595779281984 format=MP3
Feb 29, 2024 5:08:30 PM org.openaudible.Directories getPrefs
INFO: Loading C:\Users\Lee Mackinnell\OpenAudible\settings.json exists=true size=623
Feb 29, 2024 5:08:30 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1595779281984 format=MP3
Feb 29, 2024 5:08:30 PM org.openaudible.Directories getPrefs
INFO: Loading C:\Users\Lee Mackinnell\OpenAudible\settings.json exists=true size=623
Feb 29, 2024 5:08:30 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1595779281984 format=MP3
Feb 29, 2024 5:08:30 PM org.openaudible.desktop.swt.layout.Theme setTheme
INFO: Setting color theme to dark
Feb 29, 2024 5:08:30 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 4.1 win
Feb 29, 2024 5:08:30 PM org.openaudible.desktop.swt.util.shop.PaintShop prefer2x
INFO: useHighDPI=false
Feb 29, 2024 5:08:31 PM org.openaudible.Directories getPrefs
INFO: Loading C:\Users\Lee Mackinnell\OpenAudible\settings.json exists=true size=623
Feb 29, 2024 5:08:31 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1595779281984 format=MP3
Feb 29, 2024 5:08:31 PM org.openaudible.audible.AudibleConnectionState connectionChanged
INFO: Connection state changed to Connected from Not_Connected
Feb 29, 2024 5:08:31 PM org.openaudible.bookfiles.BookFiles _updateFileCache
INFO: 1. Refreshed file cache:2951 files. [] took 283 ms. to complete.
Feb 29, 2024 5:08:31 PM org.openaudible.library.BookLibrary load
INFO: Loading P:\Plex Extra\OpenAudibleFiles\books.json length 7260649
Feb 29, 2024 5:08:32 PM org.openaudible.library.BookLibrary setNeedSave
INFO: Change to library, need save flag set
Feb 29, 2024 5:08:32 PM org.openaudible.bookfiles.BookFiles _updateFileCache
INFO: 2. Refreshed file cache:2951 files. [] took 381 ms. to complete.
Feb 29, 2024 5:08:33 PM org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFO: applicationStarted took 1906 ms. to complete.
Feb 29, 2024 5:08:36 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Feb 29, 2024 5:08:41 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Manage_Accounts
Feb 29, 2024 5:08:43 PM org.openaudible.desktop.swt.manager.dialogs.ManageAccountsDialog doCommand
INFO: Test_All
Feb 29, 2024 5:08:45 PM org.openaudible.audible.api.API renewCredentials
INFO: exp=Thu Feb 29 17:58:22 AEST 2024 now=Thu Feb 29 17:08:43 AEST 2024 delta=49 minutes and 39 seconds
exp=Thu Feb 29 18:08:45 AEST 2024 now=Thu Feb 29 17:08:45 AEST 2024 delta=1 hour, 0 minute and 0 second
Feb 29, 2024 5:08:47 PM org.openaudible.audible.api.API renewCredentials
INFO: exp=Thu Feb 29 17:58:25 AEST 2024 now=Thu Feb 29 17:08:45 AEST 2024 delta=49 minutes and 40 seconds
exp=Thu Feb 29 18:08:47 AEST 2024 now=Thu Feb 29 17:08:47 AEST 2024 delta=1 hour, 0 minute and 0 second
Feb 29, 2024 5:08:50 PM org.openaudible.audible.api.API renewCredentials
INFO: exp=Thu Feb 29 17:58:28 AEST 2024 now=Thu Feb 29 17:08:47 AEST 2024 delta=49 minutes and 40 seconds
exp=Thu Feb 29 18:08:50 AEST 2024 now=Thu Feb 29 17:08:50 AEST 2024 delta=1 hour, 0 minute and 0 second
Feb 29, 2024 5:10:15 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
Feb 29, 2024 5:10:15 PM org.openaudible.desktop.swt.prefs.WindowPrefs validBounds
WARNING: Window position Rectangle {-1686, -375, 1440, 759} is not within screen area: Rectangle {50, 50, 1820, 980}
Feb 29, 2024 5:10:45 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
Feb 29, 2024 5:10:45 PM org.openaudible.desktop.swt.prefs.WindowPrefs validBounds
WARNING: Window position Rectangle {-1686, -375, 1440, 759} is not within screen area: Rectangle {50, 50, 1820, 980}
Feb 29, 2024 5:10:57 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Manage_Accounts
Feb 29, 2024 5:10:59 PM org.openaudible.desktop.swt.manager.dialogs.ManageAccountsDialog doCommand
INFO: Test_All
Feb 29, 2024 5:11:01 PM org.openaudible.audible.api.API renewCredentials
INFO: exp=Thu Feb 29 18:08:45 AEST 2024 now=Thu Feb 29 17:10:59 AEST 2024 delta=57 minutes and 45 seconds
exp=Thu Feb 29 18:11:01 AEST 2024 now=Thu Feb 29 17:11:01 AEST 2024 delta=1 hour, 0 minute and 0 second
Feb 29, 2024 5:11:03 PM org.openaudible.audible.api.API renewCredentials
INFO: exp=Thu Feb 29 18:08:50 AEST 2024 now=Thu Feb 29 17:11:01 AEST 2024 delta=57 minutes and 48 seconds
exp=Thu Feb 29 18:11:03 AEST 2024 now=Thu Feb 29 17:11:03 AEST 2024 delta=1 hour, 0 minute and 0 second
Feb 29, 2024 5:11:06 PM org.openaudible.audible.api.API renewCredentials
INFO: exp=Thu Feb 29 18:08:47 AEST 2024 now=Thu Feb 29 17:11:03 AEST 2024 delta=57 minutes and 43 seconds
exp=Thu Feb 29 18:11:06 AEST 2024 now=Thu Feb 29 17:11:06 AEST 2024 delta=1 hour, 0 minute and 0 second
Feb 29, 2024 5:11:30 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
Feb 29, 2024 5:11:30 PM org.openaudible.desktop.swt.prefs.WindowPrefs validBounds
WARNING: Window position Rectangle {-1686, -375, 1440, 759} is not within screen area: Rectangle {50, 50, 1820, 980}

**Comment by openaudible** [comment]
Shoot. That is a bug. Introduced when trying to fix the layout issues on Debian. Close and re-open the dialog. Found one other small bug.. Thanks for the report.

**Comment by openaudible** [comment]
Improving job status panel to show on conversion. (Also fixing but where it doesn't show properly if theme is set to system.

Beta shortly.

**Comment by feldegast** [comment]
my theme is set to dark just fyi, setting to system on windows
lets do a quick test....
switching between dark and system changes the "OpenAudible" text in the cover box on the main screen, set to dark it is bright white - this looks great, set to system it is a very dark grey - this is very hard to read.....

**Comment by openaudible** [comment]
Fyi going from not system to System often requires an app restart. (Long story pain in the ...)

**Comment by feldegast** [comment]
oh i am sure i just thought the colour in system theme for that text was wrong

**Comment by feldegast** [comment]
![image](https://github.com/openaudible/openaudible/assets/1029921/ffd68902-1f61-45e6-9c17-70e11736c00a)
change to system, without closing the prefrences dialogue
![image](https://github.com/openaudible/openaudible/assets/1029921/d2fdca45-a87e-4b4a-af3d-48498dba20ed)

**Comment by openaudible** [comment]
Thank you. Fixed in beta one. Put up an alert if you switch to system from another color. Fixed the account manager test bug. And now the job progress indicators go on the right side automatically (can be turned off in prefs.)

https://openaudible.org/beta

**Comment by openaudible** [comment]
Shoot. It isn't reproducible for me with beta 1. I did make a small change for beta 2 but I have no idea if it will work. If you could test that would be great.

**Comment by feldegast** [comment]
sure i can test :)

**Comment by feldegast** [comment]
Openaudible logo still broken in beta 2 when switching themes
and Account managet is also still broken after pressing test all
![image](https://github.com/openaudible/openaudible/assets/1029921/217a4cec-cb06-4d59-90c9-2aab34b2decf)

**Comment by openaudible** [comment]
Ok. Will fix. Thank you.

**Comment by feldegast** [comment]
![image](https://github.com/openaudible/openaudible/assets/1029921/462afb96-4fe8-4a8c-9c21-5653f106f8c1)
that's the broken logo with system selected as a theme

**Comment by openaudible** [comment]
Are you on Ubuntu? 
You can use any version-- this one only has a few changes since 4.1. 

Thanks

**Comment by feldegast** [comment]
i am on windows 11 (in the indider build program)

the app works fine for me i am doing these reports to help make the app better
i can use it as it is if i need to convert things right now, even the current beta

**Comment by feldegast** [comment]
![image](https://github.com/openaudible/openaudible/assets/1029921/2073e47d-c91f-4ef5-8ae8-f68822b1b570)

This is my dual screen setup, the main screen is the lower right one..... so when your app gives a negative number for a possition and the app is still filly visible it is due to it being on my left hand screen....

the log file doesn't record much in way of detail for things like this i think?

**Comment by openaudible** [comment]
I added a warning that changing from one color theme to system requires an app restart to fully switch over to the system theme.

I believe the logo will be fine if you restart the app with the system theme.  (Since it looks good in the screenshot above.)

**Comment by feldegast** [comment]
the image part of the logo always looks fine, it is the "OpenAudible" text below the picture that changes with the theme, i may be a little pedantic? i just thought the text colour shouldn't change if the background didn't change colour too
either they both should change or neither should.....

**Comment by feldegast** [comment]
https://stackoverflow.com/questions/25552/get-os-level-system-information and 
https://www.roseindia.net/java/beginners/OSInformation.shtml
have things i would have thought would be in the log file?

**Comment by openaudible** [comment]
I will add a little more. But it is all available in the diagnostics and bug reports. And most people just copy a little of the log, preferably the error message and stack trace. 

Thanks!

**Comment by feldegast** [comment]
Diagnostics has a lot of the info i agree, i have never looked at it before, i thought some of that would be helpful in the log file itself (maybe not all of it) to help identify issues for you

**Comment by feldegast** [comment]
other than the logo on the prefrences page i think this is all good now other than one word.....
on the accounts screen..... lost in translation maybe?
Libation import.... should this be Account Import?
what is Libation?

https://www.google.com/search?client=firefox-b-d&q=Libation
libation
/lʌɪˈbeɪʃn/
noun
noun: libation; plural noun: libations

    a drink [poured]
    "he poured the libation of rum on the ground"

**Comment by openaudible** [comment]
Fixed in 4.1.1.
Thank you!
