### ISSUE TITLE
Need to completely remove OpenAudible and reinstall

### ISSUE THREAD

**Issue by Geordon** [openaudible/openaudible#302]
I'm getting inconsistent error conditions with OA 1.6.6 and want to completely remove everything and reinstall it.  Can you tell me where on a Mac I would go to make sure that everything is deleted?  I mean, Library, .plist files, the whole app, etc.

Thanks!

**Comment by brand-it** [comment]
```
/Users/{user_name}/Library/OpenAudible
```
That has most of the tmp data, also deleting the app will get more of it. 


```
/Applications/OpenAudible.app/
```
you can also remove the app but I don't think must data is in there. At least anything custom to your user

**Comment by openaudible** [comment]
Can you explain what you're seeing? We released 1.6.6 last night.. Always want to make sure we didn't break anything.

**Comment by Geordon** [comment]
I've gotten a bunch of issues with it reading the Audible pages. My default browser is Brave, I have ad blocking extensions installed in Safari, and I connect to a VPN for my standard connection.  I have reset my browser to Safari and disabled all of my extensions.  I still have the same things happening.

My Audible library has 21 pages in it, at 20 items per page and one page with 14 items on it, for a total of 434 audiobooks in my library.  A Quick Sync looks at pages 1-23, which shows a page like the attached.  I am thinking that's by design, to make sure that it finds the end of the library.

Anyway, I frequently get an error popup saying "Unable to connect right now.  Try logging on to Audible from this web page and try again" when running both full and quick sync.  I thought that it might be a timeout issue, so I defaulted back to Safari and no extensions and turned off my VPN.  I am still getting that error off and on.

Additionally, OpenAudible only finds the items off of the first page on its own.  If I manually change the page in the minibrowser window, it will fill those items.  I was able to get all of the items in my library into OpenAudible by manually changing the page, and am now happily downloading them, but I'm not sure  what (if?) anything can be done to help make OpenAudible see all of the pages correctly on it's own.

**Comment by Drudoo** [comment]
I updated on debian using the deb file. Now i cant connect to audible. Tried on windows with a fresh install, syncing the library says there are no new items, even though it's a fresh install without anything synced.

**Comment by openaudible** [comment]
We have a pretty detailed log output. You could check that for errors. I'm also getting reports that Audible is radically changing their library browser, which will break OpenAudible.. so feel free to post screenshots. 
For the deb version, does the Browser window work? If so, you should be able to log into your audible account.. Anyway, sounds like a lot of issues. Try it on windows? :)

**Comment by openaudible** [comment]
This may be related to #306

**Comment by Drudoo** [comment]
It is related to #306 at least the windows issue. On debian the browser wont log in. Might be because i run headless and use VNC to access OpenAudible, but it worked a couple of months ago when i last synced my books.
