### ISSUE TITLE
Invalid key for hash

### ISSUE THREAD

**Issue by Markus1231** [openaudible/openaudible#457]
the following error pops up, when I try to convert my audiobooks:

![image](https://user-images.githubusercontent.com/71940253/94346192-4966ce00-002b-11eb-82a7-39ca8bbab40b.png)

I tried downloading the file in the audible app and copy-pasting it to openaudible and also downloading it directly in the openaudible app, same error.
I can listen to the book in the audible app, when downloaded but can't convert it.

**Comment by openaudible** [comment]
Usually deleting and re-downloading from the Audible using the OpenAudible browser is all that is needed. 
Try deleting the book (and all its files) and try one more time. If that doesn't work, we can do a scan on it if you send a report via:
https://openaudible.org/check.html

**Comment by Markus1231** [comment]
I tried re-downloading it serveral times, with the openaudible browser and with audible. also tried reinstalling openaudible. The problem occurs with all books I downloaded for the last 3 days or so. I uploaded a file for you just now. "Arabian Sands_B07CMFQLS2_LC_32_22050_Mono.aax"

**Comment by openaudible** [comment]
The book you uploaded has a different hash than the one you posted above. (74dc902a35eab6f275714562ec09f12c198639a2)
Try converting again. Or try drag and dropping that aax file onto OpenAudible. Check the logs and or post them here.. or submit a bug report after trying to convert. It should be working.

**Comment by Markus1231** [comment]
yes, all books I downloaded recently didn't work, i uploaded the smallest file that didn't work. The one I uploaded for you works now.
I still have this problem with 2 books at the moment.
Tried downloading it different ways again.



** Book 1 Downloaded with openaudible browser:**

Meta data has been saved for review. Thank you.

{
 "chapters": [
  {
   "start_time": "0.000000",
   "time_base": "1/22050",
   "start": 0,
   "end_time": "1616.898322",
   "end": 35652608,
   "id": 0,
   "tags": {"title": "Chapter 1"}
  },
  {
   "start_time": "1616.898322",
   "time_base": "1/22050",
   "start": 35652608,
   "end_time": "3131.350204",
   "end": 69046272,
   "id": 1,
   "tags": {"title": "Chapter 2"}
  },
  {
   "start_time": "3131.350204",
   "time_base": "1/22050",
   "start": 69046272,
   "end_time": "8678.458050",
   "end": 191360000,
   "id": 2,
   "tags": {"title": "Chapter 3"}
  },
  {
   "start_time": "8678.458050",
   "time_base": "1/22050",
   "start": 191360000,
   "end_time": "11494.759909",
   "end": 253459456,
   "id": 3,
   "tags": {"title": "Chapter 4"}
  },
  {
   "start_time": "11494.759909",
   "time_base": "1/22050",
   "start": 253459456,
   "end_time": "13291.566440",
   "end": 293079040,
   "id": 4,
   "tags": {"title": "Chapter 5"}
  },
  {
   "start_time": "13291.566440",
   "time_base": "1/22050",
   "start": 293079040,
   "end_time": "14125.673651",
   "end": 311471104,
   "id": 5,
   "tags": {"title": "Chapter 6"}
  },
  {
   "start_time": "14125.673651",
   "time_base": "1/22050",
   "start": 311471104,
   "end_time": "16440.517370",
   "end": 362513408,
   "id": 6,
   "tags": {"title": "Chapter 7"}
  },
  {
   "start_time": "16440.517370",
   "time_base": "1/22050",
   "start": 362513408,
   "end_time": "17594.363356",
   "end": 387955712,
   "id": 7,
   "tags": {"title": "Chapter 8"}
  },
  {
   "start_time": "17594.363356",
   "time_base": "1/22050",
   "start": 387955712,
   "end_time": "19712.301859",
   "end": 434656256,
   "id": 8,
   "tags": {"title": "Chapter 9"}
  },
  {
   "start_time": "19712.301859",
   "time_base": "1/22050",
   "start": 434656256,
   "end_time": "20796.162902",
   "end": 458555392,
   "id": 9,
   "tags": {"title": "Chapter 10"}
  },
  {
   "start_time": "20796.162902",
   "time_base": "1/22050",
   "start": 458555392,
   "end_time": "22302.952200",
   "end": 491780096,
   "id": 10,
   "tags": {"title": "Chapter 11"}
  },
  {
   "start_time": "22302.952200",
   "time_base": "1/22050",
   "start": 491780096,
   "end_time": "23354.583946",
   "end": 514968576,
   "id": 11,
   "tags": {"title": "Chapter 12"}
  },
  {
   "start_time": "23354.583946",
   "time_base": "1/22050",
   "start": 514968576,
   "end_time": "24283.475011",
   "end": 535450624,
   "id": 12,
   "tags": {"title": "Chapter 13"}
  },
  {
   "start_time": "24283.475011",
   "time_base": "1/22050",
   "start": 535450624,
   "end_time": "25649.040544",
   "end": 565561344,
   "id": 13,
   "tags": {"title": "Chapter 14"}
  },
  {
   "start_time": "25649.040544",
   "time_base": "1/22050",
   "start": 565561344,
   "end_time": "26779.713016",
   "end": 590492672,
   "id": 14,
   "tags": {"title": "Chapter 15"}
  },
  {
   "start_time": "26779.713016",
   "time_base": "1/22050",
   "start": 590492672,
   "end_time": "28236.347211",
   "end": 622611456,
   "id": 15,
   "tags": {"title": "Chapter 16"}
  },
  {
   "start_time": "28236.347211",
   "time_base": "1/22050",
   "start": 622611456,
   "end_time": "31072.711111",
   "end": 685153280,
   "id": 16,
   "tags": {"title": "Chapter 17"}
  },
  {
   "start_time": "31072.711111",
   "time_base": "1/22050",
   "start": 685153280,
   "end_time": "33331.362540",
   "end": 734956544,
   "id": 17,
   "tags": {"title": "Chapter 18"}
  },
  {
   "start_time": "33331.362540",
   "time_base": "1/22050",
   "start": 734956544,
   "end_time": "35150.924626",
   "end": 775077888,
   "id": 18,
   "tags": {"title": "Chapter 19"}
  },
  {
   "start_time": "35150.924626",
   "time_base": "1/22050",
   "start": 775077888,
   "end_time": "35848.173424",
   "end": 790452224,
   "id": 19,
   "tags": {"title": "Chapter 20"}
  },
  {
   "start_time": "35848.173424",
   "time_base": "1/22050",
   "start": 790452224,
   "end_time": "37761.590567",
   "end": 832643072,
   "id": 20,
   "tags": {"title": "Chapter 21"}
  },
  {
   "start_time": "37761.590567",
   "time_base": "1/22050",
   "start": 832643072,
   "end_time": "38799.104580",
   "end": 855520256,
   "id": 21,
   "tags": {"title": "Chapter 22"}
  },
  {
   "start_time": "38799.104580",
   "time_base": "1/22050",
   "start": 855520256,
   "end_time": "39794.218957",
   "end": 877462528,
   "id": 22,
   "tags": {"title": "Chapter 23"}
  },
  {
   "start_time": "39794.218957",
   "time_base": "1/22050",
   "start": 877462528,
   "end_time": "41276.720181",
   "end": 910151680,
   "id": 23,
   "tags": {"title": "Chapter 24"}
  },
  {
   "start_time": "41276.720181",
   "time_base": "1/22050",
   "start": 910151680,
   "end_time": "42168.784399",
   "end": 929821696,
   "id": 24,
   "tags": {"title": "Chapter 25"}
  },
  {
   "start_time": "42168.784399",
   "time_base": "1/22050",
   "start": 929821696,
   "end_time": "44919.605986",
   "end": 990477312,
   "id": 25,
   "tags": {"title": "Chapter 26"}
  },
  {
   "start_time": "44919.605986",
   "time_base": "1/22050",
   "start": 990477312,
   "end_time": "46651.907483",
   "end": 1028674560,
   "id": 26,
   "tags": {"title": "Chapter 27"}
  },
  {
   "start_time": "46651.907483",
   "time_base": "1/22050",
   "start": 1028674560,
   "end_time": "49665.021678",
   "end": 1095113728,
   "id": 27,
   "tags": {"title": "Chapter 28"}
  },
  {
   "start_time": "49665.021678",
   "time_base": "1/22050",
   "start": 1095113728,
   "end_time": "52092.157098",
   "end": 1148632064,
   "id": 28,
   "tags": {"title": "Chapter 29"}
  },
  {
   "start_time": "52092.157098",
   "time_base": "1/22050",
   "start": 1148632064,
   "end_time": "53929.830748",
   "end": 1189152768,
   "id": 29,
   "tags": {"title": "Chapter 30"}
  },
  {
   "start_time": "53929.830748",
   "time_base": "1/22050",
   "start": 1189152768,
   "end_time": "54910.130794",
   "end": 1210768384,
   "id": 30,
   "tags": {"title": "Chapter 31"}
  },
  {
   "start_time": "54910.130794",
   "time_base": "1/22050",
   "start": 1210768384,
   "end_time": "57418.628934",
   "end": 1266080768,
   "id": 31,
   "tags": {"title": "Chapter 32"}
  },
  {
   "start_time": "57418.628934",
   "time_base": "1/22050",
   "start": 1266080768,
   "end_time": "59866.894512",
   "end": 1320065024,
   "id": 32,
   "tags": {"title": "Chapter 33"}
  },
  {
   "start_time": "59866.894512",
   "time_base": "1/22050",
   "start": 1320065024,
   "end_time": "61139.255147",
   "end": 1348120576,
   "id": 33,
   "tags": {"title": "Chapter 34"}
  },
  {
   "start_time": "61139.255147",
   "time_base": "1/22050",
   "start": 1348120576,
   "end_time": "61292.106667",
   "end": 1351490952,
   "id": 34,
   "tags": {"title": "Chapter 35"}
  }
 ],
 "streams": [
  {
   "r_frame_rate": "0/0",
   "start_pts": 0,
   "channel_layout": "stereo",
   "duration_ts": 1351490952,
   "duration": "61292.106667",
   "bit_rate": "62794",
   "codec_tag_string": "aavd",
   "avg_frame_rate": "0/0",
   "nb_frames": "1319816",
   "codec_long_name": "AAC (Advanced Audio Coding)",
   "time_base": "1/22050",
   "profile": "LC",
   "index": 0,
   "max_bit_rate": "64004",
   "codec_name": "aac",
   "tags": {
    "creation_time": "2020-09-26T18:32:57.000000Z",
    "handler_name": "\u0019Apple Sound Media Handler",
    "language": "eng"
   },
   "start_time": "0.000000",
   "disposition": {
    "dub": 0,
    "karaoke": 0,
    "default": 1,
    "original": 0,
    "visual_impaired": 0,
    "forced": 0,
    "attached_pic": 0,
    "timed_thumbnails": 0,
    "comment": 0,
    "hearing_impaired": 0,
    "lyrics": 0,
    "clean_effects": 0
   },
   "codec_tag": "0x64766161",
   "sample_rate": "22050",
   "channels": 2,
   "sample_fmt": "fltp",
   "codec_time_base": "1/22050",
   "bits_per_sample": 0,
   "codec_type": "audio"
  },
  {
   "time_base": "1/22050",
   "r_frame_rate": "0/0",
   "start_pts": 0,
   "index": 1,
   "duration_ts": 1351490952,
   "codec_name": "bin_data",
   "tags": {
    "creation_time": "2020-09-26T18:33:04.000000Z",
    "handler_name": "\u0018Apple Text Media Handler",
    "language": "eng"
   },
   "duration": "61292.106667",
   "start_time": "0.000000",
   "disposition": {
    "dub": 0,
    "karaoke": 0,
    "default": 1,
    "original": 0,
    "visual_impaired": 0,
    "forced": 0,
    "attached_pic": 0,
    "timed_thumbnails": 0,
    "comment": 0,
    "hearing_impaired": 0,
    "lyrics": 0,
    "clean_effects": 0
   },
   "codec_tag": "0x74786574",
   "codec_tag_string": "text",
   "avg_frame_rate": "0/0",
   "nb_frames": "35",
   "codec_type": "data",
   "codec_long_name": "binary data"
  },
  {
   "color_range": "pc",
   "pix_fmt": "yuvj420p",
   "r_frame_rate": "90000/1",
   "start_pts": 0,
   "duration_ts": 5516289600,
   "duration": "61292.106667",
   "sample_aspect_ratio": "1:1",
   "codec_tag_string": "[0][0][0][0]",
   "avg_frame_rate": "0/0",
   "closed_captions": 0,
   "color_space": "bt470bg",
   "codec_long_name": "Motion JPEG",
   "height": 500,
   "chroma_location": "center",
   "time_base": "1/90000",
   "coded_height": 500,
   "level": -99,
   "profile": "Baseline",
   "bits_per_raw_sample": "8",
   "index": 2,
   "codec_name": "mjpeg",
   "start_time": "0.000000",
   "disposition": {
    "dub": 0,
    "karaoke": 0,
    "default": 0,
    "original": 0,
    "visual_impaired": 0,
    "forced": 0,
    "attached_pic": 1,
    "timed_thumbnails": 0,
    "comment": 0,
    "hearing_impaired": 0,
    "lyrics": 0,
    "clean_effects": 0
   },
   "codec_tag": "0x0000",
   "has_b_frames": 0,
   "refs": 1,
   "codec_time_base": "0/1",
   "width": 500,
   "display_aspect_ratio": "1:1",
   "coded_width": 500,
   "codec_type": "video"
  }
 ],
 "format": {
  "duration": "61292.106667",
  "start_time": "0.000000",
  "bit_rate": "64687",
  "filename": "/data/uploads/Leonardo da Vinci.AAX",
  "size": "495604169",
  "probe_score": 100,
  "nb_programs": 0,
  "format_long_name": "QuickTime / MOV",
  "nb_streams": 3,
  "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
  "tags": {
   "creation_time": "2020-09-26T18:32:57.000000Z",
   "date": "2017",
   "copyright": "©2017 Walter Isaacson (P)2017 Simon & Schuster Audio",
   "artist": "Walter Isaacson",
   "album_artist": "Walter Isaacson",
   "album": "Leonardo da Vinci",
   "major_brand": "aax ",
   "genre": "Hörbuch",
   "comment": "Chapter 35",
   "title": "Leonardo da Vinci",
   "minor_version": "1",
   "compatible_brands": "aax M4B mp42isom"
  }
 },
 "aax_hash": {
  "hash_good": true,
  "hash_ff": "8853315f5e94b45cba930a11fc2bf7869e6e03ed",
  "hash_offset": "8853315f5e94b45cba930a11fc2bf7869e6e03ed"
 }
}

----------


**Book 1 Downloaded with audible app:**


Meta data has been saved for review. Thank you.

{
 "chapters": [
  {
   "start_time": "0.000000",
   "time_base": "1/22050",
   "start": 0,
   "end_time": "1617.037642",
   "end": 35655680,
   "id": 0,
   "tags": {"title": "Chapter 1"}
  },
  {
   "start_time": "1617.037642",
   "time_base": "1/22050",
   "start": 35655680,
   "end_time": "3131.489524",
   "end": 69049344,
   "id": 1,
   "tags": {"title": "Chapter 2"}
  },
  {
   "start_time": "3131.489524",
   "time_base": "1/22050",
   "start": 69049344,
   "end_time": "8678.597370",
   "end": 191363072,
   "id": 2,
   "tags": {"title": "Chapter 3"}
  },
  {
   "start_time": "8678.597370",
   "time_base": "1/22050",
   "start": 191363072,
   "end_time": "11494.899229",
   "end": 253462528,
   "id": 3,
   "tags": {"title": "Chapter 4"}
  },
  {
   "start_time": "11494.899229",
   "time_base": "1/22050",
   "start": 253462528,
   "end_time": "13291.705760",
   "end": 293082112,
   "id": 4,
   "tags": {"title": "Chapter 5"}
  },
  {
   "start_time": "13291.705760",
   "time_base": "1/22050",
   "start": 293082112,
   "end_time": "14125.812971",
   "end": 311474176,
   "id": 5,
   "tags": {"title": "Chapter 6"}
  },
  {
   "start_time": "14125.812971",
   "time_base": "1/22050",
   "start": 311474176,
   "end_time": "16440.656689",
   "end": 362516480,
   "id": 6,
   "tags": {"title": "Chapter 7"}
  },
  {
   "start_time": "16440.656689",
   "time_base": "1/22050",
   "start": 362516480,
   "end_time": "17594.502676",
   "end": 387958784,
   "id": 7,
   "tags": {"title": "Chapter 8"}
  },
  {
   "start_time": "17594.502676",
   "time_base": "1/22050",
   "start": 387958784,
   "end_time": "19712.441179",
   "end": 434659328,
   "id": 8,
   "tags": {"title": "Chapter 9"}
  },
  {
   "start_time": "19712.441179",
   "time_base": "1/22050",
   "start": 434659328,
   "end_time": "20796.302222",
   "end": 458558464,
   "id": 9,
   "tags": {"title": "Chapter 10"}
  },
  {
   "start_time": "20796.302222",
   "time_base": "1/22050",
   "start": 458558464,
   "end_time": "22303.091519",
   "end": 491783168,
   "id": 10,
   "tags": {"title": "Chapter 11"}
  },
  {
   "start_time": "22303.091519",
   "time_base": "1/22050",
   "start": 491783168,
   "end_time": "23354.723265",
   "end": 514971648,
   "id": 11,
   "tags": {"title": "Chapter 12"}
  },
  {
   "start_time": "23354.723265",
   "time_base": "1/22050",
   "start": 514971648,
   "end_time": "24283.614331",
   "end": 535453696,
   "id": 12,
   "tags": {"title": "Chapter 13"}
  },
  {
   "start_time": "24283.614331",
   "time_base": "1/22050",
   "start": 535453696,
   "end_time": "25649.179864",
   "end": 565564416,
   "id": 13,
   "tags": {"title": "Chapter 14"}
  },
  {
   "start_time": "25649.179864",
   "time_base": "1/22050",
   "start": 565564416,
   "end_time": "26779.852336",
   "end": 590495744,
   "id": 14,
   "tags": {"title": "Chapter 15"}
  },
  {
   "start_time": "26779.852336",
   "time_base": "1/22050",
   "start": 590495744,
   "end_time": "28236.486531",
   "end": 622614528,
   "id": 15,
   "tags": {"title": "Chapter 16"}
  },
  {
   "start_time": "28236.486531",
   "time_base": "1/22050",
   "start": 622614528,
   "end_time": "31072.850431",
   "end": 685156352,
   "id": 16,
   "tags": {"title": "Chapter 17"}
  },
  {
   "start_time": "31072.850431",
   "time_base": "1/22050",
   "start": 685156352,
   "end_time": "33331.501859",
   "end": 734959616,
   "id": 17,
   "tags": {"title": "Chapter 18"}
  },
  {
   "start_time": "33331.501859",
   "time_base": "1/22050",
   "start": 734959616,
   "end_time": "35151.063946",
   "end": 775080960,
   "id": 18,
   "tags": {"title": "Chapter 19"}
  },
  {
   "start_time": "35151.063946",
   "time_base": "1/22050",
   "start": 775080960,
   "end_time": "35848.312744",
   "end": 790455296,
   "id": 19,
   "tags": {"title": "Chapter 20"}
  },
  {
   "start_time": "35848.312744",
   "time_base": "1/22050",
   "start": 790455296,
   "end_time": "37761.729887",
   "end": 832646144,
   "id": 20,
   "tags": {"title": "Chapter 21"}
  },
  {
   "start_time": "37761.729887",
   "time_base": "1/22050",
   "start": 832646144,
   "end_time": "38799.243900",
   "end": 855523328,
   "id": 21,
   "tags": {"title": "Chapter 22"}
  },
  {
   "start_time": "38799.243900",
   "time_base": "1/22050",
   "start": 855523328,
   "end_time": "39794.358277",
   "end": 877465600,
   "id": 22,
   "tags": {"title": "Chapter 23"}
  },
  {
   "start_time": "39794.358277",
   "time_base": "1/22050",
   "start": 877465600,
   "end_time": "41276.859501",
   "end": 910154752,
   "id": 23,
   "tags": {"title": "Chapter 24"}
  },
  {
   "start_time": "41276.859501",
   "time_base": "1/22050",
   "start": 910154752,
   "end_time": "42168.923719",
   "end": 929824768,
   "id": 24,
   "tags": {"title": "Chapter 25"}
  },
  {
   "start_time": "42168.923719",
   "time_base": "1/22050",
   "start": 929824768,
   "end_time": "44919.745306",
   "end": 990480384,
   "id": 25,
   "tags": {"title": "Chapter 26"}
  },
  {
   "start_time": "44919.745306",
   "time_base": "1/22050",
   "start": 990480384,
   "end_time": "46652.046803",
   "end": 1028677632,
   "id": 26,
   "tags": {"title": "Chapter 27"}
  },
  {
   "start_time": "46652.046803",
   "time_base": "1/22050",
   "start": 1028677632,
   "end_time": "49665.160998",
   "end": 1095116800,
   "id": 27,
   "tags": {"title": "Chapter 28"}
  },
  {
   "start_time": "49665.160998",
   "time_base": "1/22050",
   "start": 1095116800,
   "end_time": "52092.296417",
   "end": 1148635136,
   "id": 28,
   "tags": {"title": "Chapter 29"}
  },
  {
   "start_time": "52092.296417",
   "time_base": "1/22050",
   "start": 1148635136,
   "end_time": "53929.970068",
   "end": 1189155840,
   "id": 29,
   "tags": {"title": "Chapter 30"}
  },
  {
   "start_time": "53929.970068",
   "time_base": "1/22050",
   "start": 1189155840,
   "end_time": "54910.270113",
   "end": 1210771456,
   "id": 30,
   "tags": {"title": "Chapter 31"}
  },
  {
   "start_time": "54910.270113",
   "time_base": "1/22050",
   "start": 1210771456,
   "end_time": "57418.768254",
   "end": 1266083840,
   "id": 31,
   "tags": {"title": "Chapter 32"}
  },
  {
   "start_time": "57418.768254",
   "time_base": "1/22050",
   "start": 1266083840,
   "end_time": "59867.033832",
   "end": 1320068096,
   "id": 32,
   "tags": {"title": "Chapter 33"}
  },
  {
   "start_time": "59867.033832",
   "time_base": "1/22050",
   "start": 1320068096,
   "end_time": "61139.394467",
   "end": 1348123648,
   "id": 33,
   "tags": {"title": "Chapter 34"}
  },
  {
   "start_time": "61139.394467",
   "time_base": "1/22050",
   "start": 1348123648,
   "end_time": "61292.340000",
   "end": 1351496097,
   "id": 34,
   "tags": {"title": "Chapter 35"}
  }
 ],
 "streams": [
  {
   "r_frame_rate": "0/0",
   "start_pts": 0,
   "channel_layout": "mono",
   "duration_ts": 1351496097,
   "duration": "61292.340000",
   "bit_rate": "30794",
   "codec_tag_string": "aavd",
   "avg_frame_rate": "0/0",
   "nb_frames": "1319821",
   "codec_long_name": "AAC (Advanced Audio Coding)",
   "time_base": "1/22050",
   "profile": "LC",
   "index": 0,
   "max_bit_rate": "32007",
   "codec_name": "aac",
   "tags": {
    "creation_time": "2020-09-26T19:38:10.000000Z",
    "handler_name": "\u0019Apple Sound Media Handler",
    "language": "eng"
   },
   "start_time": "0.000000",
   "disposition": {
    "dub": 0,
    "karaoke": 0,
    "default": 1,
    "original": 0,
    "visual_impaired": 0,
    "forced": 0,
    "attached_pic": 0,
    "timed_thumbnails": 0,
    "comment": 0,
    "hearing_impaired": 0,
    "lyrics": 0,
    "clean_effects": 0
   },
   "codec_tag": "0x64766161",
   "sample_rate": "22050",
   "channels": 1,
   "sample_fmt": "fltp",
   "codec_time_base": "1/22050",
   "bits_per_sample": 0,
   "codec_type": "audio"
  },
  {
   "time_base": "1/22050",
   "r_frame_rate": "0/0",
   "start_pts": 0,
   "index": 1,
   "duration_ts": 1351496097,
   "codec_name": "bin_data",
   "tags": {
    "creation_time": "2020-09-26T19:38:15.000000Z",
    "handler_name": "\u0018Apple Text Media Handler",
    "language": "eng"
   },
   "duration": "61292.340000",
   "start_time": "0.000000",
   "disposition": {
    "dub": 0,
    "karaoke": 0,
    "default": 1,
    "original": 0,
    "visual_impaired": 0,
    "forced": 0,
    "attached_pic": 0,
    "timed_thumbnails": 0,
    "comment": 0,
    "hearing_impaired": 0,
    "lyrics": 0,
    "clean_effects": 0
   },
   "codec_tag": "0x74786574",
   "codec_tag_string": "text",
   "avg_frame_rate": "0/0",
   "nb_frames": "35",
   "codec_type": "data",
   "codec_long_name": "binary data"
  },
  {
   "color_range": "pc",
   "pix_fmt": "yuvj420p",
   "r_frame_rate": "90000/1",
   "start_pts": 0,
   "duration_ts": 5516310600,
   "duration": "61292.340000",
   "sample_aspect_ratio": "1:1",
   "codec_tag_string": "[0][0][0][0]",
   "avg_frame_rate": "0/0",
   "closed_captions": 0,
   "color_space": "bt470bg",
   "codec_long_name": "Motion JPEG",
   "height": 500,
   "chroma_location": "center",
   "time_base": "1/90000",
   "coded_height": 500,
   "level": -99,
   "profile": "Baseline",
   "bits_per_raw_sample": "8",
   "index": 2,
   "codec_name": "mjpeg",
   "start_time": "0.000000",
   "disposition": {
    "dub": 0,
    "karaoke": 0,
    "default": 0,
    "original": 0,
    "visual_impaired": 0,
    "forced": 0,
    "attached_pic": 1,
    "timed_thumbnails": 0,
    "comment": 0,
    "hearing_impaired": 0,
    "lyrics": 0,
    "clean_effects": 0
   },
   "codec_tag": "0x0000",
   "has_b_frames": 0,
   "refs": 1,
   "codec_time_base": "0/1",
   "width": 500,
   "display_aspect_ratio": "1:1",
   "coded_width": 500,
   "codec_type": "video"
  }
 ],
 "format": {
  "duration": "61292.340000",
  "start_time": "0.000000",
  "bit_rate": "32687",
  "filename": "/data/uploads/Leonardo da Vinci_B075THKF5K_LC_32_22050_Mono.aax",
  "size": "250438104",
  "probe_score": 100,
  "nb_programs": 0,
  "format_long_name": "QuickTime / MOV",
  "nb_streams": 3,
  "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
  "tags": {
   "creation_time": "2020-09-26T19:38:10.000000Z",
   "date": "2017",
   "copyright": "©2017 Walter Isaacson (P)2017 Simon & Schuster Audio",
   "artist": "Walter Isaacson",
   "album_artist": "Walter Isaacson",
   "album": "Leonardo da Vinci",
   "major_brand": "aax ",
   "genre": "Hörbuch",
   "comment": "Chapter 35",
   "title": "Leonardo da Vinci",
   "minor_version": "1",
   "compatible_brands": "aax M4B mp42isom"
  }
 },
 "aax_hash": {
  "hash_good": true,
  "hash_ff": "8853315f5e94b45cba930a11fc2bf7869e6e03ed",
  "hash_offset": "8853315f5e94b45cba930a11fc2bf7869e6e03ed"
 }
}


----


**Book 2 downloaded with openaudible browser:**

Meta data has been saved for review. Thank you.

{
 "chapters": [
  {
   "start_time": "0.000000",
   "time_base": "1/44100",
   "start": 0,
   "end_time": "1334.497234",
   "end": 58851328,
   "id": 0,
   "tags": {"title": "Chapter 1"}
  },
  {
   "start_time": "1334.497234",
   "time_base": "1/44100",
   "start": 58851328,
   "end_time": "4025.086259",
   "end": 177506304,
   "id": 1,
   "tags": {"title": "Chapter 2"}
  },
  {
   "start_time": "4025.086259",
   "time_base": "1/44100",
   "start": 177506304,
   "end_time": "6430.627120",
   "end": 283590656,
   "id": 2,
   "tags": {"title": "Chapter 3"}
  },
  {
   "start_time": "6430.627120",
   "time_base": "1/44100",
   "start": 283590656,
   "end_time": "8939.891519",
   "end": 394249216,
   "id": 3,
   "tags": {"title": "Chapter 4"}
  },
  {
   "start_time": "8939.891519",
   "time_base": "1/44100",
   "start": 394249216,
   "end_time": "11241.801723",
   "end": 495763456,
   "id": 4,
   "tags": {"title": "Chapter 5"}
  },
  {
   "start_time": "11241.801723",
   "time_base": "1/44100",
   "start": 495763456,
   "end_time": "13616.065306",
   "end": 600468480,
   "id": 5,
   "tags": {"title": "Chapter 6"}
  },
  {
   "start_time": "13616.065306",
   "time_base": "1/44100",
   "start": 600468480,
   "end_time": "15837.309388",
   "end": 698425344,
   "id": 6,
   "tags": {"title": "Chapter 7"}
  },
  {
   "start_time": "15837.309388",
   "time_base": "1/44100",
   "start": 698425344,
   "end_time": "18468.571429",
   "end": 814464000,
   "id": 7,
   "tags": {"title": "Chapter 8"}
  },
  {
   "start_time": "18468.571429",
   "time_base": "1/44100",
   "start": 814464000,
   "end_time": "20998.942766",
   "end": 926053376,
   "id": 8,
   "tags": {"title": "Chapter 9"}
  },
  {
   "start_time": "20998.942766",
   "time_base": "1/44100",
   "start": 926053376,
   "end_time": "23186.889433",
   "end": 1022541824,
   "id": 9,
   "tags": {"title": "Chapter 10"}
  },
  {
   "start_time": "23186.889433",
   "time_base": "1/44100",
   "start": 1022541824,
   "end_time": "25553.304671",
   "end": 1126900736,
   "id": 10,
   "tags": {"title": "Chapter 11"}
  },
  {
   "start_time": "25553.304671",
   "time_base": "1/44100",
   "start": 1126900736,
   "end_time": "27690.864036",
   "end": 1221167104,
   "id": 11,
   "tags": {"title": "Chapter 12"}
  },
  {
   "start_time": "27690.864036",
   "time_base": "1/44100",
   "start": 1221167104,
   "end_time": "30673.002812",
   "end": 1352679424,
   "id": 12,
   "tags": {"title": "Chapter 13"}
  },
  {
   "start_time": "30673.002812",
   "time_base": "1/44100",
   "start": 1352679424,
   "end_time": "34184.068934",
   "end": 1507517440,
   "id": 13,
   "tags": {"title": "Chapter 14"}
  },
  {
   "start_time": "34184.068934",
   "time_base": "1/44100",
   "start": 1507517440,
   "end_time": "35813.111293",
   "end": 1579358208,
   "id": 14,
   "tags": {"title": "Chapter 15"}
  },
  {
   "start_time": "35813.111293",
   "time_base": "1/44100",
   "start": 1579358208,
   "end_time": "38214.240363",
   "end": 1685248000,
   "id": 15,
   "tags": {"title": "Chapter 16"}
  },
  {
   "start_time": "38214.240363",
   "time_base": "1/44100",
   "start": 1685248000,
   "end_time": "38876.519909",
   "end": 1714454528,
   "id": 16,
   "tags": {"title": "Chapter 17"}
  },
  {
   "start_time": "38876.519909",
   "time_base": "1/44100",
   "start": 1714454528,
   "end_time": "39681.207438",
   "end": 1749941248,
   "id": 17,
   "tags": {"title": "Chapter 18"}
  },
  {
   "start_time": "39681.207438",
   "time_base": "1/44100",
   "start": 1749941248,
   "end_time": "41440.211882",
   "end": 1827513344,
   "id": 18,
   "tags": {"title": "Chapter 19"}
  },
  {
   "start_time": "41440.211882",
   "time_base": "1/44100",
   "start": 1827513344,
   "end_time": "43843.918367",
   "end": 1933516800,
   "id": 19,
   "tags": {"title": "Chapter 20"}
  },
  {
   "start_time": "43843.918367",
   "time_base": "1/44100",
   "start": 1933516800,
   "end_time": "46059.194921",
   "end": 2031210496,
   "id": 20,
   "tags": {"title": "Chapter 21"}
  },
  {
   "start_time": "46059.194921",
   "time_base": "1/44100",
   "start": 2031210496,
   "end_time": "46090.846667",
   "end": 2032606338,
   "id": 21,
   "tags": {"title": "Chapter 22"}
  }
 ],
 "streams": [
  {
   "r_frame_rate": "0/0",
   "start_pts": 0,
   "channel_layout": "stereo",
   "duration_ts": 2032606338,
   "duration": "46090.846667",
   "bit_rate": "125588",
   "codec_tag_string": "aavd",
   "avg_frame_rate": "0/0",
   "nb_frames": "1984968",
   "codec_long_name": "AAC (Advanced Audio Coding)",
   "time_base": "1/44100",
   "profile": "LC",
   "index": 0,
   "max_bit_rate": "128008",
   "codec_name": "aac",
   "tags": {
    "creation_time": "2020-09-26T19:24:55.000000Z",
    "handler_name": "\u0019Apple Sound Media Handler",
    "language": "eng"
   },
   "start_time": "0.000000",
   "disposition": {
    "dub": 0,
    "karaoke": 0,
    "default": 1,
    "original": 0,
    "visual_impaired": 0,
    "forced": 0,
    "attached_pic": 0,
    "timed_thumbnails": 0,
    "comment": 0,
    "hearing_impaired": 0,
    "lyrics": 0,
    "clean_effects": 0
   },
   "codec_tag": "0x64766161",
   "sample_rate": "44100",
   "channels": 2,
   "sample_fmt": "fltp",
   "codec_time_base": "1/44100",
   "bits_per_sample": 0,
   "codec_type": "audio"
  },
  {
   "time_base": "1/44100",
   "r_frame_rate": "0/0",
   "start_pts": 0,
   "index": 1,
   "duration_ts": 2032606338,
   "codec_name": "bin_data",
   "tags": {
    "creation_time": "2020-09-26T19:25:12.000000Z",
    "handler_name": "\u0018Apple Text Media Handler",
    "language": "eng"
   },
   "duration": "46090.846667",
   "start_time": "0.000000",
   "disposition": {
    "dub": 0,
    "karaoke": 0,
    "default": 1,
    "original": 0,
    "visual_impaired": 0,
    "forced": 0,
    "attached_pic": 0,
    "timed_thumbnails": 0,
    "comment": 0,
    "hearing_impaired": 0,
    "lyrics": 0,
    "clean_effects": 0
   },
   "codec_tag": "0x74786574",
   "codec_tag_string": "text",
   "avg_frame_rate": "0/0",
   "nb_frames": "22",
   "codec_type": "data",
   "codec_long_name": "binary data"
  },
  {
   "color_range": "pc",
   "pix_fmt": "yuvj420p",
   "r_frame_rate": "90000/1",
   "start_pts": 0,
   "duration_ts": 4148176200,
   "duration": "46090.846667",
   "sample_aspect_ratio": "1:1",
   "codec_tag_string": "[0][0][0][0]",
   "avg_frame_rate": "0/0",
   "closed_captions": 0,
   "color_space": "bt470bg",
   "codec_long_name": "Motion JPEG",
   "height": 500,
   "chroma_location": "center",
   "time_base": "1/90000",
   "coded_height": 500,
   "level": -99,
   "profile": "Baseline",
   "bits_per_raw_sample": "8",
   "index": 2,
   "codec_name": "mjpeg",
   "start_time": "0.000000",
   "disposition": {
    "dub": 0,
    "karaoke": 0,
    "default": 0,
    "original": 0,
    "visual_impaired": 0,
    "forced": 0,
    "attached_pic": 1,
    "timed_thumbnails": 0,
    "comment": 0,
    "hearing_impaired": 0,
    "lyrics": 0,
    "clean_effects": 0
   },
   "codec_tag": "0x0000",
   "has_b_frames": 0,
   "refs": 1,
   "codec_time_base": "0/1",
   "width": 500,
   "display_aspect_ratio": "1:1",
   "coded_width": 500,
   "codec_type": "video"
  }
 ],
 "format": {
  "duration": "46090.846667",
  "start_time": "0.000000",
  "bit_rate": "128853",
  "filename": "/data/uploads/Network Effect.AAX",
  "size": "742370673",
  "probe_score": 100,
  "nb_programs": 0,
  "format_long_name": "QuickTime / MOV",
  "nb_streams": 3,
  "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
  "tags": {
   "creation_time": "2020-09-26T19:24:55.000000Z",
   "date": "2020",
   "copyright": "©2020 Martha Wells (P)2020 Recorded Books",
   "artist": "Martha Wells",
   "album_artist": "Martha Wells",
   "album": "Network Effect",
   "major_brand": "aax ",
   "genre": "Hörbuch",
   "comment": "Chapter 22",
   "title": "Network Effect",
   "minor_version": "1",
   "compatible_brands": "aax M4B mp42isom"
  }
 },
 "aax_hash": {
  "hash_good": true,
  "hash_ff": "8853315f5e94b45cba930a11fc2bf7869e6e03ed",
  "hash_offset": "8853315f5e94b45cba930a11fc2bf7869e6e03ed"
 }
}

**Comment by Markus1231** [comment]
Still getting this error with new downloads. Is there anything on my side I can do?

**Comment by openaudible** [comment]
I don't believe you are downloading that file using the OpenAudible application and web browser. As far as I know, we don't download or name books like the way it was saved, nor do we ever use the Mono version: "Leonardo da Vinci_B075THKF5K_LC_32_22050_Mono". We would name it something like "Leonardo da Vinchi.AAX. 
Make sure the _Mono version is deleted or moved out of your OpenAudible AAX directory--maybe it is causing problems.

Can you try the following:

Delete the book from your library (right-click delete) and check it deletes the aax.

Log in with the OpenAudible browser, go to the page of your library that has the book, and select "Download Full" button. Check for any errors in the console (CTRL-D). 
If it successfully downloads it and adds it to your library, try the conversion. Look for any errors. 

Copy and paste the console log. 

Also, check your license status under the About menu. Sometimes a license can get invalidated.

**Comment by openaudible** [comment]
OK, final answer. It looks like you somehow downloaded or got an invalid book (filename ends in Mono). Delete that and re-download using the app and you should be good to go. Send logs and reopen if any issues remain! (Sorry for the late response.)
