### ISSUE TITLE
Links on the "Picture" page view

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#565]

**Comment by oboe45** [comment]
Beta 2.4.1.5

Two screen prints :
First shows the view with no picture - note that both Author and Narrator links are present, both take me to the correct place on Audible page
Second shows same line item when using "Picture" switch - both links point to the Author Page, the Narrator link points to the Author on the Audible Page
![Screen Shot 2021-02-19 at 8 33 07 PM](https://user-images.githubusercontent.com/66213325/108579002-0287b680-72f3-11eb-8b2d-370cb304b887.png)
![Screen Shot 2021-02-19 at 8 35 42 PM](https://user-images.githubusercontent.com/66213325/108579005-03b8e380-72f3-11eb-9fed-0e1361dce12a.png)

Is this fixed in next version, it was mentioned a few beta releases ago

**Comment by openaudible** [comment]
Yes, fixed. Was trying to get some more fixes into the next version before releasing a new update. Will update soon.

**Comment by openaudible** [comment]
Released new beta. Please re-open if not fixed. 
https://openaudible.org/beta
